# -*- coding: utf-8 -*-
"""info_assign1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Gtme8jB8aI84qfh4_Bs1vwKsM9BWRf0z
"""

import json
import requests

#task-1 load and understand the data
url = "https://raw.githubusercontent.com/mitre/cti/master/enterprise-attack/enterprise-attack.json"
data = requests.get(url).json()

techniques = []

for item in data["objects"]:
    if item["type"] == "attack-pattern":
        techniques.append(item)

print("Total techniques:", len(techniques))

#task-2
def threat_score(tech):
    score = 5

    name = tech.get("name", "").lower()
    description = tech.get("description", "").lower()

    # Name-Based
    if "credential" in name:
        score += 3
    if "execution" in name:
        score += 2
    if "privilege" in name:
        score += 3
    if "persistence" in name:
        score += 2
    if "lateral" in name:
        score += 2

    # Description-Based
    if "administrator" in description:
        score += 2
    if "remote" in description:
        score += 2
    if "bypass" in description:
        score += 2
    if "stealth" in description:
        score += 1

    return score

#3
scored_techniques = []

for tech in techniques:
    name = tech.get("name", "Unknown")
    score = threat_score(tech)
    scored_techniques.append((name, score))

#4.threat prioritization
scored_techniques.sort(key=lambda x: x[1], reverse=True)

print("\nTop 10 High-Risk Techniques:\n")
for name, score in scored_techniques[:10]:
    print(name, "— Score:", score)

#5
print("\nCritical Threats (Score >= 8.9):\n")
for name, score in scored_techniques:
    if score >= 8.9:
        print(name, "— Score:", score)

